### PR TITLE
Fix Protection column for IUM processes

### PR DESCRIPTION
**Pull request by ge0rdi**
Protection column will show information for Isolated User Mode (IUM) processes now.

### CODE REVIEW

**Comment by ge0rdi** [comment]
`LsaIso.exe` is an example of IUM protected process.
SI shows protection in General tab, but Protection column in process tree is empty.

**Review by jxy-s — APPROVED** [review]
I'm okay with this. An alternative would be adding another column for `Secure (IUM)` - @dmex thoughts?

**Comment by dmex** [comment]
> adding another column for Secure (IUM)

I didn't add a separate column because there's only 2 processes and not enough to justify a column 🤔

**Review by dmex — APPROVED** [review]

**Comment by jxy-s** [comment]
> > adding another column for Secure (IUM)
> 
> I didn't add a separate column because there's only 2 processes and not enough to justify a column 🤔

Yeah, agreed. Just wanted to double check on this with you. I also prefer the consistency between the properties and the column with respect to "Protection". 👍

**Pull request merged**
