### PR TITLE
Optimized images

### PR DESCRIPTION
**Pull request by Alex-S1**
Optimized images with [oxipng](https://github.com/shssoichiro/oxipng)

### CODE REVIEW

**Comment by Alex-S1** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dmex** [comment]
@Alex-S1 

Do you know if the changes for `Units: PixelsPerCentimeter` to `Undefined` improves compatibility with WIC/GDI?

systeminformer.png Before:
```
  Filename: systeminformer.png
  Format: PNG (Portable Network Graphics)
  Mime type: image/png
  Class: DirectClass
  Geometry: 512x512+0+0
  Resolution: 37.8x37.8
  Print size: 13.545x13.545
  Units: PixelsPerCentimeter
  Colorspace: sRGB
  Type: TrueColorAlpha
  Base type: Undefined
  Endianness: Undefined
  Depth: 8-bit
  Channel depth:
    red: 8-bit
    green: 8-bit
    blue: 8-bit
    alpha: 8-bit
  Channel statistics:
    Pixels: 262144
    Red:
      min: 0  (0)
      max: 218 (0.854902)
      mean: 69.4357 (0.272297)
      standard deviation: 77.4893 (0.30388)
      kurtosis: -1.1583
      skewness: 0.531627
      entropy: 0.325035
    Green:
      min: 0  (0)
      max: 231 (0.905882)
      mean: 83.3791 (0.326977)
      standard deviation: 89.9373 (0.352695)
      kurtosis: -1.61589
      skewness: 0.321859
      entropy: 0.322069
    Blue:
      min: 0  (0)
      max: 236 (0.92549)
      mean: 97.4797 (0.382273)
      standard deviation: 104.728 (0.410699)
      kurtosis: -1.77945
      skewness: 0.267271
      entropy: 0.321149
    Alpha:
      min: 0  (0)
      max: 255 (1)
      mean: 198.132 (0.776988)
      standard deviation: 105.883 (0.415227)
      kurtosis: -0.223475
      skewness: -1.33084
      entropy: 0.107856
  Image statistics:
    Overall:
      min: 0  (0)
      max: 255 (1)
      mean: 112.107 (0.439634)
      standard deviation: 94.5094 (0.370625)
      kurtosis: -1.70981
      skewness: 0.136897
      entropy: 0.269027
  Alpha: none   #00000000
  Rendering intent: Perceptual
  Gamma: 0.454545
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Background color: white
  Border color: srgba(223,223,223,1)
  Matte color: grey74
  Transparent color: none
  Interlace: None
  Intensity: Undefined
  Compose: Over
  Page geometry: 512x512+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: Zip
  Orientation: Undefined
  Properties:
    date:create: 2022-12-07T16:52:23+00:00
    date:modify: 2022-07-17T04:36:40+00:00
    png:IHDR.bit-depth-orig: 8
    png:IHDR.bit_depth: 8
    png:IHDR.color-type-orig: 6
    png:IHDR.color_type: 6 (RGBA)
    png:IHDR.interlace_method: 0 (Not interlaced)
    png:IHDR.width,height: 512, 512
    png:pHYs: x_res=3780, y_res=3780, units=1
    png:sRGB: intent=0 (Perceptual Intent)
    png:text: 1 tEXt/zTXt/iTXt chunks were found
    signature: d212b4d7e9b7cc0a3087a32073f9852def0ef4f70bebd5a15ca2ed6259725941
    Software: www.inkscape.org
  Artifacts:
    filename: systeminformer.png
    verbose: true
  Tainted: False
  Filesize: 38045B
  Number pixels: 262144
  Pixels per second: 54.7742MB
  User time: 0.000u
  Elapsed time: 0:01.004
  ```

systeminformer.png After: 
```
  Filename: systeminformer.png
  Format: PNG (Portable Network Graphics)
  Mime type: image/png
  Class: DirectClass
  Geometry: 512x512+0+0
  Units: Undefined
  Colorspace: sRGB
  Type: TrueColorAlpha
  Base type: Undefined
  Endianness: Undefined
  Depth: 8-bit
  Channel depth:
    red: 8-bit
    green: 8-bit
    blue: 8-bit
    alpha: 8-bit
  Channel statistics:
    Pixels: 262144
    Red:
      min: 0  (0)
      max: 218 (0.854902)
      mean: 69.4357 (0.272297)
      standard deviation: 77.4893 (0.30388)
      kurtosis: -1.1583
      skewness: 0.531627
      entropy: 0.325035
    Green:
      min: 0  (0)
      max: 231 (0.905882)
      mean: 83.3791 (0.326977)
      standard deviation: 89.9373 (0.352695)
      kurtosis: -1.61589
      skewness: 0.321859
      entropy: 0.322069
    Blue:
      min: 0  (0)
      max: 236 (0.92549)
      mean: 97.4797 (0.382273)
      standard deviation: 104.728 (0.410699)
      kurtosis: -1.77945
      skewness: 0.267271
      entropy: 0.321149
    Alpha:
      min: 0  (0)
      max: 255 (1)
      mean: 198.132 (0.776988)
      standard deviation: 105.883 (0.415227)
      kurtosis: -0.223475
      skewness: -1.33084
      entropy: 0.107856
  Image statistics:
    Overall:
      min: 0  (0)
      max: 255 (1)
      mean: 112.107 (0.439634)
      standard deviation: 94.5094 (0.370625)
      kurtosis: -1.70981
      skewness: 0.136897
      entropy: 0.269027
  Alpha: none   #00000000
  Rendering intent: Perceptual
  Gamma: 0.454545
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Background color: white
  Border color: srgba(223,223,223,1)
  Matte color: grey74
  Transparent color: none
  Interlace: None
  Intensity: Undefined
  Compose: Over
  Page geometry: 512x512+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: Zip
  Orientation: Undefined
  Properties:
    date:create: 2023-01-16T23:00:50+00:00
    date:modify: 2023-01-16T23:00:50+00:00
    png:IHDR.bit-depth-orig: 8
    png:IHDR.bit_depth: 8
    png:IHDR.color-type-orig: 6
    png:IHDR.color_type: 6 (RGBA)
    png:IHDR.interlace_method: 0 (Not interlaced)
    png:IHDR.width,height: 512, 512
    png:sRGB: intent=0 (Perceptual Intent)
    signature: d212b4d7e9b7cc0a3087a32073f9852def0ef4f70bebd5a15ca2ed6259725941
  Artifacts:
    filename: systeminformer.png
    verbose: true
  Tainted: False
  Filesize: 26069B
  Number pixels: 262144
  Pixels per second: 68.5469MB
  User time: 0.000u
  Elapsed time: 0:01.003
  ```

active_search.png Before:
```
  Filename: active_search.png
  Format: PNG (Portable Network Graphics)
  Mime type: image/png
  Class: DirectClass
  Geometry: 27x27+0+0
  Units: Undefined
  Colorspace: sRGB
  Type: PaletteAlpha
  Base type: Undefined
  Endianness: Undefined
  Depth: 8-bit
  Channel depth:
    red: 8-bit
    green: 8-bit
    blue: 8-bit
    alpha: 8-bit
  Channel statistics:
    Pixels: 729
    Red:
      min: 0  (0)
      max: 74 (0.290196)
      mean: 5.38134 (0.0211033)
      standard deviation: 13.9917 (0.0548692)
      kurtosis: 4.50225
      skewness: 2.41568
      entropy: 0.255657
    Green:
      min: 0  (0)
      max: 145 (0.568627)
      mean: 12.9108 (0.0506307)
      standard deviation: 33.6604 (0.132002)
      kurtosis: 4.12641
      skewness: 2.39051
      entropy: 0.246134
    Blue:
      min: 0  (0)
      max: 193 (0.756863)
      mean: 19.321 (0.0757686)
      standard deviation: 49.9859 (0.196023)
      kurtosis: 3.7221
      skewness: 2.329
      entropy: 0.24306
    Alpha:
      min: 0  (0)
      max: 255 (1)
      mean: 21.9396 (0.0860378)
      standard deviation: 64.5092 (0.252977)
      kurtosis: 7.27027
      skewness: 2.98737
      entropy: 0.32825
  Image statistics:
    Overall:
      min: 0  (0)
      max: 255 (1)
      mean: 14.8882 (0.0583851)
      standard deviation: 40.5368 (0.158968)
      kurtosis: 12.5429
      skewness: 3.53475
      entropy: 0.268275
  Alpha: none   #00000000
  Colors: 47
  Histogram:
    579: (0,0,0,0) #00000000 none
    15: (0,0,0,1) #00000001 srgba(0,0,0,0.00392157)
    12: (0,0,0,3) #00000003 srgba(0,0,0,0.0117647)
    9: (0,0,0,6) #00000006 srgba(0,0,0,0.0235294)
    8: (0,0,0,13) #0000000D srgba(0,0,0,0.0509804)
    4: (0,0,0,12) #0000000C srgba(0,0,0,0.0470588)
    1: (0,0,0,21) #00000015 srgba(0,0,0,0.0823529)
    2: (12,23,36,26) #0C17241A srgba(12,23,36,0.101961)
    1: (15,32,53,14) #0F20350E srgba(15,32,53,0.054902)
    1: (20,44,70,21) #142C4615 srgba(20,44,70,0.0823529)
    5: (22,46,72,48) #162E4830 srgba(22,46,72,0.188235)
    3: (22,50,80,58) #1632503A srgba(22,50,80,0.227451)
    3: (25,63,94,48) #193F5E30 srgba(25,63,94,0.188235)
    1: (28,67,102,89) #1C436659 srgba(28,67,102,0.34902)
    3: (29,71,105,57) #1D476939 srgba(29,71,105,0.223529)
    1: (34,74,119,189) #224A77BD srgba(34,74,119,0.741176)
    1: (34,74,120,200) #224A78C8 srgba(34,74,120,0.784314)
    3: (34,76,123,228) #224C7BE4 srgba(34,76,123,0.894118)
    1: (34,82,122,88) #22527A58 srgba(34,82,122,0.345098)
    3: (35,80,128,234) #235080EA srgba(35,80,128,0.917647)
    2: (35,81,129,255) #235181FF srgba(35,81,129,1)
    4: (35,83,128,46) #2353802E srgba(35,83,128,0.180392)
    2: (35,86,132,34) #23568422 srgba(35,86,132,0.133333)
    3: (37,87,133,55) #25578537 srgba(37,87,133,0.215686)
    3: (38,88,136,234) #265888EA srgba(38,88,136,0.917647)
    2: (38,88,137,255) #265889FF srgba(38,88,137,1)
    2: (38,89,138,226) #26598AE2 srgba(38,89,138,0.886275)
    3: (39,94,143,234) #275E8FEA srgba(39,94,143,0.917647)
    2: (39,97,143,100) #27618F64 srgba(39,97,143,0.392157)
    5: (41,97,148,255) #296194FF srgba(41,97,148,1)
    2: (42,98,149,236) #2A6295EC srgba(42,98,149,0.92549)
    3: (43,104,156,255) #2B689CFF srgba(43,104,156,1)
    4: (43,111,162,44) #2B6FA22C srgba(43,111,162,0.172549)
    2: (44,107,160,229) #2C6BA0E5 srgba(44,107,160,0.898039)
    3: (44,115,169,55) #2C73A937 srgba(44,115,169,0.215686)
    3: (45,109,162,255) #2D6DA2FF srgba(45,109,162,1)
    3: (45,114,167,228) #2D72A7E4 srgba(45,114,167,0.894118)
    2: (46,114,168,255) #2E72A8FF srgba(46,114,168,1)
    3: (46,116,170,234) #2E74AAEA srgba(46,116,170,0.917647)
    2: (46,116,170,241) #2E74AAF1 srgba(46,116,170,0.945098)
    2: (46,120,177,228) #2E78B1E4 srgba(46,120,177,0.894118)
    4: (47,119,176,255) #2F77B0FF srgba(47,119,176,1)
    4: (47,123,179,238) #2F7BB3EE srgba(47,123,179,0.933333)
    1: (47,125,180,200) #2F7DB4C8 srgba(47,125,180,0.784314)
    1: (48,126,181,211) #307EB5D3 srgba(48,126,181,0.827451)
    4: (56,125,174,19) #387DAE13 srgba(56,125,174,0.0745098)
    2: (74,145,193,43) #4A91C12B srgba(74,145,193,0.168627)
  Rendering intent: Perceptual
  Gamma: 0.454545
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Background color: white
  Border color: srgba(223,223,223,1)
  Matte color: grey74
  Transparent color: none
  Interlace: None
  Intensity: Undefined
  Compose: Over
  Page geometry: 27x27+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: Zip
  Orientation: Undefined
  Properties:
    date:create: 2022-12-16T14:47:02+00:00
    date:modify: 2022-12-16T14:47:02+00:00
    png:bKGD: chunk was found (see Background color, above)
    png:IHDR.bit-depth-orig: 8
    png:IHDR.bit_depth: 8
    png:IHDR.color-type-orig: 6
    png:IHDR.color_type: 6 (RGBA)
    png:IHDR.interlace_method: 0 (Not interlaced)
    png:IHDR.width,height: 27, 27
    png:sRGB: intent=0 (Perceptual Intent)
    signature: 4959bae06fb3a5a3c4cfe54ea564cdd44899001445a8c487e7ff9de231150380
  Artifacts:
    filename: active_search.png
    verbose: true
  Tainted: False
  Filesize: 672B
  Number pixels: 729
  Pixels per second: 1.00165MB
  User time: 0.000u
  Elapsed time: 0:01.000
  ```

active_search.png After:
```
  Filename: active_search.png
  Format: PNG (Portable Network Graphics)
  Mime type: image/png
  Class: DirectClass
  Geometry: 27x27+0+0
  Units: Undefined
  Colorspace: sRGB
  Type: PaletteAlpha
  Base type: Undefined
  Endianness: Undefined
  Depth: 8-bit
  Channel depth:
    red: 8-bit
    green: 8-bit
    blue: 8-bit
    alpha: 8-bit
  Channel statistics:
    Pixels: 729
    Red:
      min: 0  (0)
      max: 74 (0.290196)
      mean: 5.38134 (0.0211033)
      standard deviation: 13.9917 (0.0548692)
      kurtosis: 4.50225
      skewness: 2.41568
      entropy: 0.255657
    Green:
      min: 0  (0)
      max: 145 (0.568627)
      mean: 12.9108 (0.0506307)
      standard deviation: 33.6604 (0.132002)
      kurtosis: 4.12641
      skewness: 2.39051
      entropy: 0.246134
    Blue:
      min: 0  (0)
      max: 193 (0.756863)
      mean: 19.321 (0.0757686)
      standard deviation: 49.9859 (0.196023)
      kurtosis: 3.7221
      skewness: 2.329
      entropy: 0.24306
    Alpha:
      min: 0  (0)
      max: 255 (1)
      mean: 21.9396 (0.0860378)
      standard deviation: 64.5092 (0.252977)
      kurtosis: 7.27027
      skewness: 2.98737
      entropy: 0.32825
  Image statistics:
    Overall:
      min: 0  (0)
      max: 255 (1)
      mean: 14.8882 (0.0583851)
      standard deviation: 40.5368 (0.158968)
      kurtosis: 12.5429
      skewness: 3.53475
      entropy: 0.268275
  Alpha: none   #00000000
  Colors: 47
  Histogram:
    579: (0,0,0,0) #00000000 none
    15: (0,0,0,1) #00000001 srgba(0,0,0,0.00392157)
    12: (0,0,0,3) #00000003 srgba(0,0,0,0.0117647)
    9: (0,0,0,6) #00000006 srgba(0,0,0,0.0235294)
    8: (0,0,0,13) #0000000D srgba(0,0,0,0.0509804)
    4: (0,0,0,12) #0000000C srgba(0,0,0,0.0470588)
    1: (0,0,0,21) #00000015 srgba(0,0,0,0.0823529)
    2: (12,23,36,26) #0C17241A srgba(12,23,36,0.101961)
    1: (15,32,53,14) #0F20350E srgba(15,32,53,0.054902)
    1: (20,44,70,21) #142C4615 srgba(20,44,70,0.0823529)
    5: (22,46,72,48) #162E4830 srgba(22,46,72,0.188235)
    3: (22,50,80,58) #1632503A srgba(22,50,80,0.227451)
    3: (25,63,94,48) #193F5E30 srgba(25,63,94,0.188235)
    1: (28,67,102,89) #1C436659 srgba(28,67,102,0.34902)
    3: (29,71,105,57) #1D476939 srgba(29,71,105,0.223529)
    1: (34,74,119,189) #224A77BD srgba(34,74,119,0.741176)
    1: (34,74,120,200) #224A78C8 srgba(34,74,120,0.784314)
    3: (34,76,123,228) #224C7BE4 srgba(34,76,123,0.894118)
    1: (34,82,122,88) #22527A58 srgba(34,82,122,0.345098)
    3: (35,80,128,234) #235080EA srgba(35,80,128,0.917647)
    2: (35,81,129,255) #235181FF srgba(35,81,129,1)
    4: (35,83,128,46) #2353802E srgba(35,83,128,0.180392)
    2: (35,86,132,34) #23568422 srgba(35,86,132,0.133333)
    3: (37,87,133,55) #25578537 srgba(37,87,133,0.215686)
    3: (38,88,136,234) #265888EA srgba(38,88,136,0.917647)
    2: (38,88,137,255) #265889FF srgba(38,88,137,1)
    2: (38,89,138,226) #26598AE2 srgba(38,89,138,0.886275)
    3: (39,94,143,234) #275E8FEA srgba(39,94,143,0.917647)
    2: (39,97,143,100) #27618F64 srgba(39,97,143,0.392157)
    5: (41,97,148,255) #296194FF srgba(41,97,148,1)
    2: (42,98,149,236) #2A6295EC srgba(42,98,149,0.92549)
    3: (43,104,156,255) #2B689CFF srgba(43,104,156,1)
    4: (43,111,162,44) #2B6FA22C srgba(43,111,162,0.172549)
    2: (44,107,160,229) #2C6BA0E5 srgba(44,107,160,0.898039)
    3: (44,115,169,55) #2C73A937 srgba(44,115,169,0.215686)
    3: (45,109,162,255) #2D6DA2FF srgba(45,109,162,1)
    3: (45,114,167,228) #2D72A7E4 srgba(45,114,167,0.894118)
    2: (46,114,168,255) #2E72A8FF srgba(46,114,168,1)
    3: (46,116,170,234) #2E74AAEA srgba(46,116,170,0.917647)
    2: (46,116,170,241) #2E74AAF1 srgba(46,116,170,0.945098)
    2: (46,120,177,228) #2E78B1E4 srgba(46,120,177,0.894118)
    4: (47,119,176,255) #2F77B0FF srgba(47,119,176,1)
    4: (47,123,179,238) #2F7BB3EE srgba(47,123,179,0.933333)
    1: (47,125,180,200) #2F7DB4C8 srgba(47,125,180,0.784314)
    1: (48,126,181,211) #307EB5D3 srgba(48,126,181,0.827451)
    4: (56,125,174,19) #387DAE13 srgba(56,125,174,0.0745098)
    2: (74,145,193,43) #4A91C12B srgba(74,145,193,0.168627)
  Rendering intent: Perceptual
  Gamma: 0.454545
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Background color: white
  Border color: srgba(223,223,223,1)
  Matte color: grey74
  Transparent color: none
  Interlace: None
  Intensity: Undefined
  Compose: Over
  Page geometry: 27x27+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: Zip
  Orientation: Undefined
  Properties:
    date:create: 2023-01-16T23:11:43+00:00
    date:modify: 2023-01-16T23:11:43+00:00
    png:IHDR.bit-depth-orig: 8
    png:IHDR.bit_depth: 8
    png:IHDR.color-type-orig: 3
    png:IHDR.color_type: 3 (Indexed)
    png:IHDR.interlace_method: 0 (Not interlaced)
    png:IHDR.width,height: 27, 27
    png:PLTE.number_colors: 47
    png:sRGB: intent=0 (Perceptual Intent)
    png:tRNS: chunk was found
    signature: 4959bae06fb3a5a3c4cfe54ea564cdd44899001445a8c487e7ff9de231150380
  Artifacts:
    filename: active_search.png
    verbose: true
  Tainted: False
  Filesize: 426B
  Number pixels: 729
  Pixels per second: 1.10204MB
  User time: 0.000u
  Elapsed time: 0:01.000
  ```

**Review by dmex — APPROVED** [review]

**Comment by Alex-S1** [comment]
Hi dmex.
No, I don't.

**Comment by dmex** [comment]
> Hi dmex. No, I don't.

The format is still sRGB which is what GDI wants. I don't see any issues👍

**Pull request merged**
